### ISSUE TITLE
This package barely does anything

### ISSUE THREAD

**Issue by dandv** [risul/meteor-mandrill-api#2]
One line, really. We have have more full-featured wrappers:
- https://github.com/timmyg/meteor-mandrill
- https://github.com/Wylio/meteor-mandrill/
- https://github.com/mjmasn/mandrill/

**Comment by risul** [comment]
@dandv: while appreciate your efforts for more quality package, whether a package has 1 line of code or a million, should not be the benchmark of usefullnes of the package.

I created this package to simply to wrap Mandrill's node.js rest API AS IS.

The other packages you've mentioned try to try to be more than a wrapper, which is not what I need/want to do.

Hope this helps clarifying the use case!

Thanks!

**Comment by dandv** [comment]
Much better! Now the package is practically identical to @mjmasn's

https://github.com/mjmasn/mandrill/blob/master/mandrill.coffee
vs.
https://github.com/risul/meteor-mandrill-api/blob/master/lib/mandrill.js
